// Code generated by go generate; DO NOT EDIT.
// This file was generated by evoli at
// 2022-09-20 12:56:58.254435 +0200 CEST m=+0.012517710
package main

import (
	"embed"
	"github.com/evolidev/evoli"
	"simple/components"
	"simple/routes"
)

//go:embed resources public configs
var content embed.FS

func (app *TestApp) Start() {
	app.Application = evoli.NewApplication()
	app.Application.AddEmbedFS(content)
	app.Application.AddRoutes("/api", routes.Api)
	app.Application.AddRoutes("/", routes.Files)
	app.Application.AddRoutes("/assets", routes.Folders)
	app.Application.AddRoutes("/", routes.Web)
	app.Application.RegisterComponent(components.Init{})
	app.Application.RegisterComponent(components.Input{})
	app.Application.RegisterComponent(components.Login{})

	app.Application.Start()
}
