name: Main

on:
  push:
    branches:
    - main

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3

    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.18.0'

    - name: Lint go files
      uses: golangci/golangci-lint-action@v2

    - name: Run vet
      run: |
        make vet
    - name: Run test
      run: |
        go test ./test