name: Main

on:
  push:
    branches:
    - main

jobs:

  build:
    runs-on: golang-latest
    steps:
    - uses: actions/checkout@v3

    - name: Run test
      run: |
        go version
        go vet .
        go test ./test