name: Main

on:
  push:
    branches:
    - main

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3

    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: '>=1.19.0'

    - name: Run test
      run: |
        go version
        go install golang.org/x/lint/golint
        go mod tidy
        go vet .
        golint .
        go test ./test